name: Playground CI

on:
  push:
    branches: [ "main" ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello, World!"
      - name: List all files
        run: ls -R